[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "simplepackage"
dist-name = "simplepackage.py"
author = "Jakub Kuczys"
classifiers = [ "License :: OSI Approved :: MIT License",]
